### ISSUE TITLE
TNT Tag bug , Sumo Event no death when falling void even water 

### ISSUE THREAD

**Issue by LittleLostZ** [FrozedClubDevelopment/FrostCommunity#34]
### Expected behavior

[15:25:57] [Server thread/WARN]: [Frost] Task #47501 for Frost v8.7 generated an exception
java.lang.NullPointerException: null
    at me.elb1to.practice.managers.EventManager.addSpectator(EventManager.java:116) ~[?:?]
    at me.elb1to.practice.events.games.tnttag.TNTTagEvent.lambda$onDeath$3(TNTTagEvent.java:80) ~[?:?]
    at me.elb1to.practice.events.games.tnttag.TNTTagEvent.lambda$explodePlayer$5(TNTTagEvent.java:123) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
    at me.elb1to.practice.events.games.tnttag.TNTTagEvent.explodePlayer(TNTTagEvent.java:118) ~[?:?]
    at me.elb1to.practice.events.games.tnttag.TNTTagEvent$TNTTagTask.run(TNTTagEvent.java:291) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[Spigot.jar:git-Carbon-392abd8]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:351) ~[Spigot.jar:git-Carbon-392abd8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797) ~[Spigot.jar:git-Carbon-392abd8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409) ~[Spigot.jar:git-Carbon-392abd8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:727) ~[Spigot.jar:git-Carbon-392abd8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:624) ~[Spigot.jar:git-Carbon-392abd8]
    at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

### Observed/Actual behavior

https://media.discordapp.net/attachments/943506011409510480/974226665351815168/2022-05-12_15-26-34.mp4

### How to Recreate (if known)

Sumo Event: when I knock player down to void & they don't die even  I use water still no respawn

TNT Tag issue when they blow up they still pickup tnt to tag someone 

### Stack trace

I dont have pastebin :l

### Plugin list

Frost
Aquacore
Verus
Vulcan
Multicore
Viaversion
...

### Frost version

Frost 8.7

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
This issue has been successfully fixed and it's bugfix will be available for the v10.0 release of Frost.
