### ISSUE TITLE
Arena Copies not working

### ISSUE THREAD

**Issue by herobrine407** [FrozedClubDevelopment/FrostCommunity#57]
### Expected behavior

When clicking  on the amount of copies I want it should create the amount of arenas desired.

### Observed/Actual behavior

When copying the arenas there is an error in the console, and then the config of that entire arena deletes itself, sometimes even deleting the whole contents of the "arena.yml" file.

### How to Recreate (if known)

Just make a copy of an arena.

### Stack trace

`java.lang.NullPointerException
        at me.elb1to.practice.util.cuboid.Cuboid.<init>(Cuboid.java:47) ~[?:?]
        at me.elb1to.practice.managers.chunk.restoration.impl.FrostChunkRestoration.copy(FrostChunkRestoration.java:27) ~[?:?]
        at me.elb1to.practice.managers.ArenaManager.lambda$null$0(ArenaManager.java:75) ~[?:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.elb1to.practice.managers.ArenaManager.lambda$loadArenas$1(ArenaManager.java:63) ~[?:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.elb1to.practice.managers.ArenaManager.loadArenas(ArenaManager.java:44) ~[?:?]
        at me.elb1to.practice.managers.ArenaManager.reloadArenas(ArenaManager.java:91) ~[?:?]
        at me.elb1to.practice.runnable.ArenaCommandRunnable$1.onComplete(ArenaCommandRunnable.java:68) ~[?:?]
        at me.elb1to.practice.runnable.DuplicateArenaRunnable$1.finish(DuplicateArenaRunnable.java:75) ~[?:?]
        at me.elb1to.practice.runnable.BlockPlaceRunnable.run(BlockPlaceRunnable.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:411) [FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:876) [FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:382) [FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:806) [FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:708) [FoxSpigot.jar:1.8.8-R0.1-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]`

### Plugin list

![image](https://user-images.githubusercontent.com/85850822/223294893-9663e29e-1857-4690-8532-dc192e20660f.png)

### Frost version

Version:  v12.3

### Confirmations

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Are you sure that followed every step to create an arena before making copies of it?

**Comment by herobrine407** [comment]
Yep, I set the icon, the a location, the b location, the min corner, the max corner, the buildmax, the deadzone. I didn't set the portalprot cause it's not necessary.

The message says that All the copies were pasted successfully but they weren't.

**Comment by Elb1to** [comment]
Issue solved.
The cause was a misconfiguration problem.
